# Generated by Django 3.0.8 on 2020-08-14 10:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee', models.DecimalField(decimal_places=0, max_digits=6, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Fee')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('declined_at', models.DateTimeField(blank=True, null=True, verbose_name='Declined at')),
                ('accepted_at', models.DateTimeField(blank=True, null=True, verbose_name='Accepted at')),
                ('changes_requested', models.BooleanField(default=False, verbose_name='Changes requested')),
            ],
            options={
                'verbose_name': 'Offer',
                'verbose_name_plural': 'Offers',
                'db_table': 'offers',
                'ordering': ('-created_at',),
            },
        ),
    ]
