# Generated by Django 3.0.8 on 2020-08-14 10:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('offers', '0001_initial'),
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to=settings.AUTH_USER_MODEL, verbose_name='Artist'),
        ),
        migrations.AddField(
            model_name='offer',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='orders.Order', verbose_name='Order info'),
        ),
        migrations.AlterUniqueTogether(
            name='offer',
            unique_together={('order', 'artist')},
        ),
    ]
