# Generated by Django 3.0.8 on 2020-08-24 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20200814_1007'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='views',
            field=models.PositiveIntegerField(default=0, verbose_name='Views count'),
        ),
    ]
