# Generated by Django 3.0.8 on 2020-08-14 10:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tags', '0001_initial'),
        ('files', '0001_initial'),
        ('masterpieces', '0001_initial'),
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='masterpiece',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='masterpieces', to=settings.AUTH_USER_MODEL, verbose_name='Artist'),
        ),
        migrations.AddField(
            model_name='masterpiece',
            name='files',
            field=models.ManyToManyField(blank=True, related_name='masterpieces', to='files.File'),
        ),
        migrations.AddField(
            model_name='masterpiece',
            name='order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='masterpiece', to='orders.Order', verbose_name='Order'),
        ),
        migrations.AddField(
            model_name='masterpiece',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='masterpieces', to='tags.Tag'),
        ),
    ]
